local lfs = require("lfs")
local Alter = require("orm.migrations.alter")
local ValueHelper = require("orm.helpers.value")

local MIGRATION_TEMPLATE = [=[local Migration = {}
Migration.version = %q

--- @param migrationBuilder MigrationBuilder
function Migration.up(migrationBuilder)
%s
end

--- @param migrationBuilder MigrationBuilder
function Migration.down(migrationBuilder)
%s
end

return Migration
]=]

local APPLIED_SCHEMA_TEMPLATE = [=[-- WARNING: DO NOT EDIT THIS FILE; IT IS GENERATED AUTOMATICALLY BY THE MIGRATION GENERATOR
-- EDITING IT WILL CAUSE UNEXPECTED BEHAVIOUR

%s

return {
%s
}
]=]

local Requires = {
    TYPES = 'local Types = require("orm.model.types")',
    CONSTRAINT = 'local Constraint = require("orm.model.constraint")',
    ALTER = 'local Alter = require("orm.migrations.alter")',
    CURRENT_TIMESTAMP = 'local CurrentTimestamp = require("orm.model.expressions.current-timestamp")',
    MODEL = 'local Model = require("orm.model")',
}

local MigrationBuilderMethods = {
    CREATE_TABLE = "migrationBuilder:createTable(%q, {\n\t\t%s\n\t})",
    DROP_TABLE = "migrationBuilder:dropTable(%q)",
    ALTER_TABLE = "migrationBuilder:alterTable(%q, {\n\t\t%s\n\t})"
}

--- @param str string
local function toSnakeCase(str)
    return str:lower()
        :gsub("[^%w]+", "_") -- non-alphanumeric to underscore
        :gsub("^_+", ""):gsub("_+$", "") -- trim leading/trailing underscores
end

--- @return string
local function timestamp()
    return tostring(os.date("%Y%m%d%H%M%S"))
end

--- @param path string
local function ensureDirectoryExists(path)
    local accum = path:sub(1, 1) == "/" and "/" or ""
    for segment in path:gmatch("[^/]+") do
        if accum == "" then
            accum = segment
        elseif accum == "/" then
            accum = accum .. segment
        else
            accum = accum .. "/" .. segment
        end
        local attr = lfs.attributes(accum)
        if not attr then
            local ok, err = lfs.mkdir(accum)
            if not ok then
                return nil, err
            end
        elseif attr.mode ~= "directory" then
            return nil, accum .. " exists and is not a directory"
        end
    end
    return true
end

--- @class MigrationGenerator
--- @field name string
--- @field context DbContext
--- @field migrationsDirectory string
local MigrationGenerator = {}
MigrationGenerator.__index = MigrationGenerator
MigrationGenerator.SCHEMA_SNAPSHOT_FILENAME = "_schema_snapshot.lua"

--- @param name string
--- @param context DbContext
function MigrationGenerator.new(name, context)
    assert(name ~= nil, "Failed to construct MigrationGenerator: migration name must not be nil")
    assert(context ~= nil, "Failed to construct MigrationGenerator: context must not be nil")
    assert(context.config.migrationsDir ~= nil, "Failed to construct MigrationGenerator: migrationsDirectory must not be nil or an empty string")

    return setmetatable({
        name = name,
        context = context,
        migrationsDirectory = context.config.migrationsDir or "migrations",
    }, MigrationGenerator)
end

--- @param modelClass ModelClass
--- @param oldField Field
--- @param newField Field
--- @return ColumnAlteration[]
function MigrationGenerator:getFieldDiff(modelClass, oldField, newField)
    local compiler = self.context:getCompiler()
    local diff = {}

    -- This assert should never error but if it does, it means the fields have different names and the field must be renamed
    assert(oldField.name == newField.name, "Failed to get field diff: Fields must have matching names, got " .. oldField.name .. " and " .. newField.name .. " of model '" .. modelClass.tableName .. "'")

    local typeChanged = not oldField.type:equals(newField.type)
    if typeChanged then -- PostgreSQL may reject a type change while the old default is attached.
        if oldField.default ~= nil then
            table.insert(diff, Alter.dropColumnDefault(oldField.name))
        end
        table.insert(diff, Alter.setColumnType(oldField.name, newField.type))
    end

    if oldField.nullable ~= newField.nullable and newField.nullable then
        table.insert(diff, Alter.dropColumnNotNull(newField.name))
    elseif oldField.nullable ~= newField.nullable then
        table.insert(diff, Alter.setColumnNotNull(newField.name))
    end

    if oldField.unique ~= newField.unique and newField.unique then
        table.insert(diff,
            Alter.addUniqueKeyConstraint(compiler:getUniqueKeyConstraintName(modelClass.tableName, newField.name),
                newField.name))
    elseif oldField.unique ~= newField.unique then
        table.insert(diff, Alter.dropConstraint(compiler:getUniqueKeyConstraintName(modelClass.tableName, newField.name)))
    end

    local oldForeignKey = oldField.foreignKey
    local newForeignKey = newField.foreignKey
    local foreignKeyChanged = (oldForeignKey == nil) ~= (newForeignKey == nil)
        or (oldForeignKey and newForeignKey
            and (oldForeignKey.referenceTable ~= newForeignKey.referenceTable
                or oldForeignKey.referenceColumn ~= newForeignKey.referenceColumn))

    if foreignKeyChanged then
        local constraintName = compiler:getForeignKeyConstraintName(modelClass.tableName, newField.name)
        if oldForeignKey then
            table.insert(diff, Alter.dropConstraint(constraintName))
        end
        if newForeignKey then
            table.insert(diff, Alter.addForeignKeyConstraint(
                constraintName,
                newField.name,
                newForeignKey.referenceTable,
                newForeignKey.referenceColumn))
        end
    end

    if not ValueHelper.equals(oldField.default, newField.default) or typeChanged then
        if newField.default == nil then
            if not typeChanged then
                table.insert(diff, Alter.dropColumnDefault(newField.name))
            end
        else
            table.insert(diff, Alter.setColumnDefault(newField.name, newField.default))
        end
    end

    if oldField.autoIncrement ~= newField.autoIncrement then
        if newField.autoIncrement then
            table.insert(diff, Alter.addColumnAutoIncrement(newField.name, newField.identityMode))
        else
            table.insert(diff, Alter.dropColumnIdentity(newField.name))
        end
    elseif newField.autoIncrement and oldField.identityMode ~= newField.identityMode then
        -- in theory, identity mode will never be set to nil if autoIncrement is true,
        -- there must be a default (unless some other database provider does differently), so the only case is:
        -- oldField.identityMode = ALWAYS, newField.identityMode = GENERATED_AS_IDENTITY or vice versa, as for now
        table.insert(diff, Alter.setColumnIdentity(newField.name, newField.identityMode))
    end

    if oldField.primaryKey ~= newField.primaryKey then
        -- oldField = false, newField = true
        -- oldField = true, newField = false
        -- both are exclusive, if newField is true, oldField must be false, and vice versa
        if newField.primaryKey then
            table.insert(diff,
                Alter.addPrimaryKeyConstraint(compiler:getPrimaryKeyConstraintName(modelClass.tableName), newField.name))
        else
            table.insert(diff, Alter.dropConstraint(compiler:getPrimaryKeyConstraintName(modelClass.tableName)))
        end
    end

    return diff
end

--- @class ModelClassDiff
--- @field addedFields Field[]
--- @field removedFields Field[]
--- @field alterations Alteration[]
--- @field reverseAlterations Alteration[]
--- @field oldModel ModelClass
--- @field newModel ModelClass

--- @class SchemaDiff
--- @field removed table<string, ModelClass>
--- @field added table<string, ModelClass>
--- @field altered table<string, ModelClassDiff>
function MigrationGenerator:getSchemaDiff()
    --- @type table<string, ModelClass>
    local schemaSnapshot = {}
    --- @type table<string, ModelClass>
    local definedSchema = self.context.modelClasses

    -- Load applied schema from file
    local schemaSnapshotPath = string.format("%s/%s", self.migrationsDirectory, self.SCHEMA_SNAPSHOT_FILENAME)
    local schemaSnapshotExists = lfs.attributes(schemaSnapshotPath)
    if schemaSnapshotExists then
        local snapshotModule = require(schemaSnapshotPath:gsub("/", "."):sub(1, -5))
        schemaSnapshot = snapshotModule
    else
        print("No applied schema found, starting with an empty schema.")
    end

    local diff = {
        removed = {},
        added = {},
        altered = {}
    }

    -- Check for removed or altered models
    for _, modelClass in pairs(schemaSnapshot) do
        local definedModel = definedSchema[modelClass.tableName]
        if definedModel == nil then
            -- TODO: check for table rename, maybe not in here
            diff.removed[modelClass.tableName] = modelClass
        else
            --- @type ModelClassDiff
            local modelDiff = {
                removedFields = {},
                addedFields = {},
                alterations = {},
                reverseAlterations = {},
                oldModel = modelClass,
                newModel = definedModel,
            }

            -- First check for removed or altered fields
            for _, field in ipairs(modelClass.fields) do
                local definedField = definedModel.fieldsByName[field.name]
                if definedField == nil then
                    -- TODO: Detect renames
                    table.insert(modelDiff.removedFields, field)
                else
                    -- Then check for altered fields
                    for _, fieldDiff in ipairs(self:getFieldDiff(modelClass, field, definedField)) do
                        table.insert(modelDiff.alterations, fieldDiff)
                    end
                    for _, fieldDiff in ipairs(self:getFieldDiff(definedModel, definedField, field)) do
                        table.insert(modelDiff.reverseAlterations, fieldDiff)
                    end
                end
            end

            -- Then check for added fields, they do are new and don't need alter
            for _, field in ipairs(definedModel.fields) do
                if modelClass.fieldsByName[field.name] == nil then
                    table.insert(modelDiff.addedFields, field)
                end
            end

            if #modelDiff.addedFields > 0 or #modelDiff.removedFields > 0 or #modelDiff.alterations > 0 then
                diff.altered[modelClass.tableName] = modelDiff
            end
        end
    end

    -- Check for added models, models that were added do not need altering as they are new
    for _, modelClass in pairs(definedSchema) do
        if schemaSnapshot[modelClass.tableName] == nil then
            diff.added[modelClass.tableName] = modelClass
        end
    end

    return diff
end

--- Returns model names in dependency order, so referenced tables precede tables with foreign keys.
--- Self-referencing foreign keys do not affect table creation order.
--- @param models table<string, ModelClass>
--- @return string[]
local function orderModelsByDependencies(models)
    local names = {}
    for name in pairs(models) do
        table.insert(names, name)
    end
    table.sort(names)

    local ordered, state, stack = {}, {}, {}

    local function visit(name)
        if state[name] == "visited" then
            return
        end
        if state[name] == "visiting" then
            table.insert(stack, name)
            error("Cannot order tables with circular foreign-key dependencies: " .. table.concat(stack, " -> "))
        end

        state[name] = "visiting"
        table.insert(stack, name)

        local dependencies = {}
        for _, field in ipairs(models[name].fields) do
            local referenceTable = field.foreignKey and field.foreignKey.referenceTable
            if referenceTable and referenceTable ~= name and models[referenceTable] then
                dependencies[referenceTable] = true
            end
        end

        local dependencyNames = {}
        for dependencyName in pairs(dependencies) do
            table.insert(dependencyNames, dependencyName)
        end
        table.sort(dependencyNames)
        for _, dependencyName in ipairs(dependencyNames) do
            visit(dependencyName)
        end

        table.remove(stack)
        state[name] = "visited"
        table.insert(ordered, name)
    end

    for _, name in ipairs(names) do
        visit(name)
    end

    return ordered
end

--- @param values any[]
local function reverse(values)
    local reversed = {}
    for index = #values, 1, -1 do
        table.insert(reversed, values[index])
    end
    return reversed
end

local ALTERATION_PRIORITY = {
    [Alter.Kinds.DROP_CONSTRAINT] = 10,
    [Alter.Kinds.ADD_COLUMN] = 40,
    [Alter.Kinds.ADD_CONSTRAINT] = 80,
    [Alter.Kinds.DROP_COLUMN] = 90,
}

local COLUMN_OPERATION_PRIORITY = {
    [Alter.ColumnOperation.DROP_IDENTITY] = 20,
    [Alter.ColumnOperation.DROP_DEFAULT] = 21,
    [Alter.ColumnOperation.DROP_NOT_NULL] = 22,
    [Alter.ColumnOperation.SET_TYPE] = 30,
    [Alter.ColumnOperation.SET_DEFAULT] = 50,
    [Alter.ColumnOperation.SET_NOT_NULL] = 51,
    [Alter.ColumnOperation.ADD_AUTO_INCREMENT] = 52,
    [Alter.ColumnOperation.SET_IDENTITY] = 53,
    [Alter.ColumnOperation.RENAME] = 60,
}

--- @param alterations Alteration[]
local function sortAlterations(alterations)
    table.sort(alterations, function(left, right)
        local leftPriority = left.kind == Alter.Kinds.ALTER_COLUMN
            and COLUMN_OPERATION_PRIORITY[left.operation] or ALTERATION_PRIORITY[left.kind]
        local rightPriority = right.kind == Alter.Kinds.ALTER_COLUMN
            and COLUMN_OPERATION_PRIORITY[right.operation] or ALTERATION_PRIORITY[right.kind]

        assert(leftPriority, "Missing ordering priority for alteration " .. tostring(left.kind))
        assert(rightPriority, "Missing ordering priority for alteration " .. tostring(right.kind))

        if leftPriority ~= rightPriority then
            return leftPriority < rightPriority
        end

        local leftKey = left.column or left.columnName or left.name or left.field.name
        local rightKey = right.column or right.columnName or right.name or right.field.name
        if leftKey ~= rightKey then
            return leftKey < rightKey
        end

        return left:toCode() < right:toCode()
    end)
end

--- @param modelDiff ModelClassDiff
--- @param reverseDirection boolean
--- @return Alteration[]
local function getTableAlterations(modelDiff, reverseDirection)
    local alterations = {}
    local fieldAlterations = reverseDirection and modelDiff.reverseAlterations or modelDiff.alterations
    local addedFields = reverseDirection and modelDiff.removedFields or modelDiff.addedFields
    local removedFields = reverseDirection and modelDiff.addedFields or modelDiff.removedFields

    for _, alteration in ipairs(fieldAlterations) do
        table.insert(alterations, alteration)
    end
    for _, field in ipairs(addedFields) do
        table.insert(alterations, Alter.addColumn(field))
    end
    for _, field in ipairs(removedFields) do
        table.insert(alterations, Alter.dropColumn(field.name))
    end

    sortAlterations(alterations)
    return alterations
end

--- @param modelClass ModelClass
local function fieldsToCode(modelClass)
    local definitions = {}
    for _, field in ipairs(modelClass.fields) do
        table.insert(definitions, field:definitionToCode())
    end
    return table.concat(definitions, ",\n\t\t")
end

--- @param statements string[]
local function migrationBody(statements)
    if #statements == 0 then
        return "\t-- No schema changes."
    end
    return "\t" .. table.concat(statements, "\n\n\t")
end

--- @param modelClasses table<string, ModelClass>
--- @return string
local function generateSchemaContent(modelClasses)
    local requires = {
        Requires.MODEL,
        Requires.TYPES,
        Requires.CONSTRAINT,
        Requires.CURRENT_TIMESTAMP
    }

    local modelDefinitions = {}
    for _, modelClass in pairs(modelClasses) do
        table.insert(modelDefinitions, ("[%q] = Model(%q, {\n\t\t%s\n\t})"):format(modelClass.tableName, modelClass.tableName, fieldsToCode(modelClass)))
    end

    return APPLIED_SCHEMA_TEMPLATE:format(table.concat(requires, "\n"), "\t" .. table.concat(modelDefinitions, ",\n\n\t"))
end

function MigrationGenerator:generate()
    local directoryCreated, directoryError = ensureDirectoryExists(self.migrationsDirectory)
    assert(directoryCreated, "Failed to create migrations directory: " .. tostring(directoryError))

    local slug = toSnakeCase(self.name)
    assert(slug ~= "", string.format("Migration name '%s' produced an empty slug after sanitization", self.name))

    local requires = {
        Requires.TYPES,
        Requires.CONSTRAINT,
        Requires.ALTER,
        Requires.CURRENT_TIMESTAMP,
    }
    local up = {}
    local down = {}

    local schemaDiff = self:getSchemaDiff()

    -- Up: referenced new tables first, existing-table changes next, dependent removals last.
    for _, tableName in ipairs(orderModelsByDependencies(schemaDiff.added)) do
        local modelClass = schemaDiff.added[tableName]
        table.insert(up, MigrationBuilderMethods.CREATE_TABLE:format(tableName, fieldsToCode(modelClass)))
    end

    local alteredNames = {}
    for tableName in pairs(schemaDiff.altered) do
        table.insert(alteredNames, tableName)
    end
    table.sort(alteredNames)
    for _, tableName in ipairs(alteredNames) do
        local alterations = getTableAlterations(schemaDiff.altered[tableName], false)
        local alterationCode = {}
        for _, alteration in ipairs(alterations) do
            table.insert(alterationCode, alteration:toCode())
        end
        table.insert(up, MigrationBuilderMethods.ALTER_TABLE:format(tableName, table.concat(alterationCode, ", ")))
    end

    for _, tableName in ipairs(reverse(orderModelsByDependencies(schemaDiff.removed))) do
        table.insert(up, MigrationBuilderMethods.DROP_TABLE:format(tableName))
    end

    -- Down mirrors Up: restore removed dependencies, undo alterations, then remove added dependents.
    for _, tableName in ipairs(orderModelsByDependencies(schemaDiff.removed)) do
        local modelClass = schemaDiff.removed[tableName]
        table.insert(down, MigrationBuilderMethods.CREATE_TABLE:format(tableName, fieldsToCode(modelClass)))
    end

    for _, tableName in ipairs(alteredNames) do
        local alterations = getTableAlterations(schemaDiff.altered[tableName], true)
        local alterationCode = {}
        for _, alteration in ipairs(alterations) do
            table.insert(alterationCode, alteration:toCode())
        end
        table.insert(down, MigrationBuilderMethods.ALTER_TABLE:format(tableName, table.concat(alterationCode, ", ")))
    end

    for _, tableName in ipairs(reverse(orderModelsByDependencies(schemaDiff.added))) do
        table.insert(down, MigrationBuilderMethods.DROP_TABLE:format(tableName))
    end

    local migrationVersion = string.format("%s_%s", timestamp(), slug)
    local migrationFilename = string.format("%s.lua", migrationVersion)
    local migrationPath = string.format("%s/%s", self.migrationsDirectory, migrationFilename)
    local schemaSnapshotPath = string.format("%s/%s", self.migrationsDirectory, self.SCHEMA_SNAPSHOT_FILENAME)

    local migrationFile, migration_open_error = io.open(migrationPath, "w")
    assert(migrationFile, string.format("Failed to create migration file '%s': %s", migrationPath, tostring(migration_open_error)))

    local schemaSnapshotFile, schemaSnapshotOpenError = io.open(schemaSnapshotPath, "w")
    assert(schemaSnapshotFile, string.format("Failed to create applied schema file '%s': %s", schemaSnapshotPath, tostring(schemaSnapshotOpenError)))

    local migrationFileContent = MIGRATION_TEMPLATE:format(migrationVersion, migrationBody(up), migrationBody(down))
    migrationFileContent = table.concat(requires, "\n") .. "\n\n" .. migrationFileContent

    migrationFile:write(migrationFileContent)
    schemaSnapshotFile:write(generateSchemaContent(self.context.modelClasses))

    migrationFile:close()
    schemaSnapshotFile:close()

    return migrationPath
end

return MigrationGenerator
